# Generated by Django 5.0.2 on 2024-02-19 09:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='author',
            fields=[
                ('author_id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('email_id', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('phone_number', models.BigIntegerField(null=True)),
                ('photo', models.CharField(max_length=50)),
                ('login_id', models.IntegerField()),
                ('membership', models.CharField(default='Not Member', max_length=50)),
            ],
            options={
                'db_table': 'tbl_author',
            },
        ),
        migrations.CreateModel(
            name='author_book',
            fields=[
                ('author_book_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_id', models.IntegerField()),
                ('author_login_id', models.IntegerField()),
                ('language_id', models.IntegerField()),
                ('type', models.IntegerField()),
                ('book_name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('doc', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'tbl_author_book',
            },
        ),
        migrations.CreateModel(
            name='book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_id', models.IntegerField()),
                ('author_id', models.IntegerField()),
                ('language_id', models.IntegerField()),
                ('type', models.IntegerField()),
                ('book_name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('doc', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'tbl_book',
            },
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tbl_category',
            },
        ),
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('complaint_id', models.AutoField(primary_key=True, serialize=False)),
                ('complaint_subject', models.CharField(max_length=50)),
                ('complaint', models.CharField(max_length=150)),
                ('user_login_id', models.IntegerField()),
                ('reply', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tbl_complaint',
            },
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback_subject', models.CharField(max_length=50)),
                ('feedback', models.TextField()),
                ('user_login_id', models.IntegerField()),
                ('reply', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tbl_feedback',
            },
        ),
        migrations.CreateModel(
            name='language',
            fields=[
                ('language_id', models.AutoField(primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tbl_language',
            },
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('login_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.TextField(null=True)),
                ('Usertype', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tbl_login',
            },
        ),
        migrations.CreateModel(
            name='membership_amount',
            fields=[
                ('membership_amount_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'db_table': 'tbl_membership_amount',
            },
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_id', models.IntegerField()),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('entry_date', models.DateTimeField(default=datetime.datetime.now)),
                ('user_login_id', models.IntegerField()),
                ('check_no_order', models.IntegerField()),
            ],
            options={
                'db_table': 'tbl_order',
            },
        ),
        migrations.CreateModel(
            name='user_register',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('login_id', models.IntegerField()),
                ('Name', models.CharField(max_length=50, null=True)),
                ('phone_number', models.BigIntegerField(null=True)),
                ('Email', models.CharField(max_length=50)),
                ('Address', models.TextField()),
            ],
            options={
                'db_table': 'tbl_customer_register',
            },
        ),
    ]
