# Generated by Django 5.0 on 2024-02-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='author_name',
            fields=[
                ('author_id', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=50)),
                ('about_author', models.TextField()),
            ],
            options={
                'db_table': 'tbl_author_name',
            },
        ),
    ]
