# Generated by Django 5.0 on 2024-02-21 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0002_author_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='doc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='type',
            field=models.CharField(max_length=50),
        ),
    ]
