# Generated by Django 5.0 on 2024-02-22 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0005_alter_order_check_no_order_alter_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='user_type',
            field=models.CharField(default='Admin', max_length=50),
        ),
    ]
