# Generated by Django 5.0 on 2024-02-23 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0007_book_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='fee',
            fields=[
                ('fee_id', models.AutoField(primary_key=True, serialize=False)),
                ('fee', models.IntegerField()),
            ],
            options={
                'db_table': 'tbl_fee',
            },
        ),
    ]
