# Generated by Django 5.0 on 2024-02-23 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0008_fee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='author_book',
        ),
        migrations.AddField(
            model_name='author',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
